### ISSUE TITLE
Having issues on a 1.7.1 Server with a 1.8 Data pack.

### ISSUE THREAD

**Issue by K9Paradox** [joogle12/SeedCracker#2]
Cannot collect bits from the server, only dungeon bits, and the viewer doesn't appear to be working either. Been trying to grab the seed from this server for a week now.

**Comment by CB30** [comment]
> Cannot collect bits from the server, only dungeon bits, and the viewer doesn't appear to be working either. Been trying to grab the seed from this server for a week now.

could be using custom generation or anti-xray.
