### ISSUE TITLE
Search Unsuccessful

### ISSUE THREAD

**Issue by thmsmntro** [joogle12/SeedCracker#3]
Used the seed cracker and gathered enough bits, however the seed cracker returned with no results. Is there something I did wrong? I used the original in 1.15 and it worked fine, just wanted to make sure I hadn't messed up anything.

Attached is the log report (unsure if helpful)
[latest.log](https://github.com/CB30/SeedCracker/files/6857256/latest.log)

**Comment by CB30** [comment]
> Used the seed cracker and gathered enough bits, however the seed cracker returned with no results. Is there something I did wrong? I used the original in 1.15 and it worked fine, just wanted to make sure I hadn't messed up anything.
> 
> Attached is the log report (unsure if helpful)
> [latest.log](https://github.com/CB30/SeedCracker/files/6857256/latest.log)

what dimension are you cracking in? If in overworld, the server might be using anti-xray which covers part of the dungeon floor. If so, mine out the dungeon so the whole floor is visible.
